Repository creek0810/loveat2, pull requests merged in 2019-12, with the labels that each got.

#48 Speed up loading on menu page
  static/js/menu.js
  templates/menu.html
Labels: enhancement

#52 Finish push lib
  .eslintrc.js
  lib/push.py
  main.py
  static/favicon.ico
  static/js/lib/firebase-messaging-sw.js
  static/js/lib/push-default.js
  static/js/lib/push-init.js
  templates/layout.html
  views/order_api.py
  views/root.py
Labels: enhancement

#51 fix: fix cart item quantity and register age value
  static/js/loveat2-cart.js
  templates/cart.html
  templates/component/register.html
Labels: bug

#50 Enhance model
  models/menu.py
  models/order.py
Labels: enhancement

#49 Finish update profile api
  models/image.py
  models/user.py
  static/img/default.png
  templates/layout.html
  views/root.py
  views/user_api.py
Labels: enhancement

#57 Finish order push
  lib/push.py
  models/order.py
  views/order_api.py
  views/root.py
  views/user_api.py
Labels: enhancement

#28 Set business time
  models/business_time.py
  static/css/business-time.css
  static/js/business_time.js
  templates/business_time.html
  views/setting_web.py
Labels: enhancement

#60 Fix some bug
  models/menu.py
  static/js/loveat2-cart.js
Labels: bug

#58 Fix push bug
  models/order.py
  static/js/lib/push-init.js
  templates/component/navbar.html
  views/user_api.py
Labels: bug

#61 Push to admin when order state update to doing
  models/order.py
  static/js/lib/firebase-messaging-sw.js
  tests/test_order.py
  views/order_api.py
Labels: enhancement

#54 finish order state page
  static/css/order-state.css
  static/css/order.css
  static/js/lib/firebase-messaging-sw.js
  static/js/order-state.js
  static/js/order.js
  templates/order-state.html
  templates/order.html
  views/order_web.py
Labels: enhancement

#62 Refactor the part of connecting to db
  models/business_time.py
  models/db.py
  models/image.py
  models/menu.py
  models/order.py
  models/user.py
  tests/conftest.py
  tests/test_item.py
  tests/test_order.py
  tests/test_setting.py
  tests/test_type.py
  tests/test_user.py
Labels: enhancement

#64 Extend projection mode to get item, combo by id
  models/menu.py
Labels: enhancement

#66 Enhance validate for new order
  models/order.py
Labels: enhancement

#67 Fix incorrect analysis order data
  models/order.py
Labels: bug

#59 Todo
  models/order.py
  static/css/todo.css
  static/js/order.js
  static/js/todo.js
  templates/todo.html
  views/order_web.py
Labels: enhancement

#68 Enhance cart check
  static/js/loveat2-cart.js
  templates/cart.html
  tests/test_user.py
  views/order_web.py
Labels: bug, enhancement

#70 Auto login after user register success
  models/user.py
  static/js/auth.js
  views/user_api.py
Labels: enhancement

#72 Fix chart refresh bug
  static/js/history-data-chart.js
  static/js/history.js
  static/js/lib/history-chart.js
  templates/history.html
Labels: bug

#73 Correct the quantity input string problem
  static/js/loveat2-cart.js
Labels: bug

#77 Add status code for adding type api
  models/menu.py
  views/menu_api.py
Labels: enhancement

#75 Finish profile feature
  models/user.py
  static/css/profile.css
  static/js/lib/fetch-data.js
  static/js/profile.js
  templates/profile.html
  views/menu_web.py
  views/order_web.py
  views/setting_web.py
  views/user_web.py
Labels: enhancement

#78 Order history - replace '0' with '-' on history analysis page
  static/js/history.js
Labels: enhancement

#79 Store item description input by users
  static/js/lib/cart.js
  static/js/loveat2-cart.js
  templates/order-state.html
  templates/order.html
Labels: enhancement

#74 Edit menu
  static/css/edit-add-combo.css
  static/css/edit-add-item.css
  static/css/menu-edit.css
  static/js/edit-add-combo.js
  static/js/edit-add-item.js
  static/js/menu-edit.js
  templates/edit-add-combo.html
  templates/edit-add-item.html
  templates/menu-edit.html
  views/menu_api.py
  views/menu_web.py
Labels: enhancement

#82 Advise new item/combo css and navbar brand
  models/user.py
  static/css/edit-add-combo.css
  static/css/edit-add-item.css
  templates/component/navbar.html
  views/user_web.py
Labels: enhancement

#85 Fix menu api
  models/menu.py
  package-lock.json
  package.json
  views/menu_api.py
Labels: bug, enhancement

#83 Check item quantity, enhance menu page
  static/css/menu.css
  static/js/lib/cart.js
  static/js/loveat2-cart.js
  static/js/menu.js
  templates/menu.html
Labels: bug, enhancement

#87 Fix update item combo api
  .travis.yml
  models/menu.py
Labels: bug

#86 feat: finish update item/combo, and fix menu-edit
  package.json
  static/js/edit-add-combo.js
  static/js/edit-add-item.js
  static/js/menu-edit.js
  templates/edit-add-combo.html
  templates/edit-add-item.html
  templates/menu-edit.html
  views/menu_web.py
Labels: enhancement

#89 Profile page rwd
  static/css/profile.css
  templates/profile.html
Labels: enhancement

#92 speed up connecting to gmail
  lib/send_email.py
Labels: enhancement

#90 style: cart page rwd
  .vscode/settings.json
  Pipfile
  static/css/cart.css
  static/js/loveat2-cart.js
  templates/cart.html
Labels: enhancement

#88 Menu page rwd
  .gitignore
  .vscode/settings.json
  static/css/menu.css
  templates/component/navbar.html
  templates/menu.html
Labels: enhancement

#94 Add test
  tests/conftest.py
  tests/data/combo.json
  tests/data/image.json
  tests/data/order.json
  tests/data/user.json
  tests/test_combo.py
  tests/test_item.py
  tests/test_order.py
  tests/test_type.py
  tests/test_user.py
Labels: test

#95 style: finish menu-edit RWD and modify cart CSS
  static/css/cart.css
  static/css/edit-add-combo.css
  static/css/menu-edit.css
  static/js/edit-add-item.js
  templates/cart.html
  templates/menu-edit.html
Labels: enhancement

#102 Add foolproof mechanism for todo page
  static/js/todo.js
  templates/todo.html
Labels: enhancement
